const accordionData = [
  {
    title: "Programming Languages",
    content: ["JavaScript", "TypeScript", "Java", "Python"],
  },
  {
    title: "Web Technologies",
    content: [
      "NodeJS",
      "ReactJS",
      "HTML5",
      "CSS/CSS3",
      "LESS",
      "Bootstrap",
      "AngularJS",
      "jQuery",
      "ES6",
      "JSP",
      "Redux",
      "Babel",
      "Webpack",
      "NPM",
      "AJAX",
      "MVC",
      "Cookies",
      "Local Storage",
      "Accessibility (a11y)",
      "Jest",
      "XML",
      "JSON",
      "CORS",
      "YAML",
      "Mocha",
      "Karma",
      "REST",
      "GaphQL",
      "Shell Scripting",
      "Linux",
    ],
  },
  {
    title: "Tools/Platforms",
    content: [
      "SVN",
      "Git",
      "Bitbucket",
      "Figma",
      "Tomcat",
      "JIRA",
      "Maven",
      "Jenkins",
      "Confluence",
      "Postman",
      "Eclipse",
      "IntelliJ",
      "MySQL",
      "AWS",
    ],
  },
];

export default accordionData;
