const accordionData = [
  {
    title: "Programming Languages",
    content: ["JavaScript", "TypeScript", "Java", "Python", "SQL", "C++"],
  },
  {
    title: "Web Technologies",
    content: [
      "Node.js",
      "React.js",
      "HTML5",
      "CSS/CSS3",
      "LESS",
      "SASS",
      "Bootstrap",
      "Angular.js",
      "jQuery",
      "ES6",
      "JSP",
      "Redux",
      "Babel",
      "Webpack",
      "NPM",
      "nginx",
      "AJAX",
      "MVC",
      "Cookies",
      "Accessibility (a11y)",
      "Jest",
      "XML",
      "JSON",
      "CORS",
      "YAML",
      "Karma",
      "REST",
      "GaphQL",
      "Shell Scripting",
      "Linux"
    ],
  },
  {
    title: "Databases & Tools",
    content: ["MySQL", "MongoDB/NoSQL", "SQL Server", "PowerBI", "Lucidchart", "dBeaver"],
  },
  {
    title: "Tools/Platforms",
    content: [
      "SVN",
      "Git",
      "Bitbucket",
      "Figma",
      "Tomcat",
      "JIRA",
      "Maven",
      "Jenkins",
      "Confluence",
      "Postman",
      "Eclipse",
      "IntelliJ",
      "Jupyter Notebok",
      "Anaconda",
      "Pycharm",
      "Colab",
      "Notion",
      "AWS",
      "Canva"
    ],
  },
];

export default accordionData;
